### ISSUE TITLE
".use" method of Server not typed

### ISSUE THREAD

**Issue by Lange** [phiresky/typed-socket.io#2]
Howdy,

I (unfortunately) use Socket.IO's middleware functionality in my app, which is done via the `.use()` method. It seems that when casting my server instance to a TypedServer, this method is not included in those typedefs.

**Comment by Lange** [comment]
Sorry, I'm a fool and made a very simple mistake. Everythings fine. 🤠

**Comment by phiresky** [comment]
No problem :) 
Middlewares work, though they sadly can't really be fully correctly typed in many cases (since they can modify the type of the corresponding socket).
